name: 'Label Actions'

on:
  issues:
    types: unlabeled
  pull_request:
    types: unlabeled
  discussion:
    types: unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2